class AddIndexes < ActiveRecord::Migration
  def change
    add_index :bad_logins, :created_at
    add_index :bad_logins, :email
    add_index :bad_logins, :ip
    add_index :carts, :confirmation_email
    add_index :carts, :payment_method
    add_index :carts, :payment_name
    add_index :carts, :status
    add_index :carts, :user_id
    add_index :clubs, :active
    add_index :clubs, :city
    add_index :clubs, :county
    add_index :clubs, :name
    add_index :downloads, :data_content_type
    add_index :episodes, :number
    add_index :events, :category
    add_index :fees, :active
    add_index :fees, :end_date
    add_index :fees, :name
    add_index :fees, :sale_end
    add_index :fees, :sale_start
    add_index :fees, :start_date
    add_index :fees, :type
    add_index :items, :cart_id
    add_index :items, :end_date
    add_index :items, :fee_id
    add_index :items, :payment_method
    add_index :items, :player_id
    add_index :items, :source
    add_index :items, :start_date
    add_index :items, :status
    add_index :items, :type
    add_index :journal_entries, :action
    add_index :journal_entries, :by
    add_index :journal_entries, :column
    add_index :journal_entries, :ip
    add_index :journal_entries, :journalable_id
    add_index :journal_entries, :journalable_type
    add_index :logins, :error
    add_index :logins, :ip
    add_index :logins, :user_id
    add_index :payment_errors, :cart_id
    add_index :payment_errors, :confirmation_email
    add_index :players, :club_id
    add_index :players, :dob
    add_index :players, :fed
    add_index :players, :gender
    add_index :players, :joined
    add_index :players, :player_id
    add_index :players, :source
    add_index :players, :status
    add_index :refunds, :cart_id
    add_index :refunds, :created_at
    add_index :refunds, :user_id
    add_index :translations, :active
    add_index :translations, :english
    add_index :translations, :key
    add_index :translations, :user
    add_index :translations, :value
    add_index :user_inputs, :fee_id
    add_index :user_inputs, :type
    add_index :users, :email
    add_index :users, :expires_on
    add_index :users, :player_id
    add_index :users, :roles
    add_index :users, :status
    add_index :users, :verified_at
  end
end
